# Generated by Django 3.0.3 on 2020-03-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200314_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='static/%Y/%m/%d'),
        ),
    ]
